# -*- coding: utf-8 -*-

"""
Django settings for bPortal project.

Generated by 'django-admin startproject' using Django 1.11.5.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os
import logging
from logging.handlers import TimedRotatingFileHandler

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'timed_rotating_file': {
            'level': 'ERROR',
            'class': 'logging.handlers.TimedRotatingFileHandler',
            'filename': os.path.join(BASE_DIR, 'django_error.log'),
            'when': 'midnight',  # Rotate logs at midnight
            'interval': 1,
            'backupCount': 7,    # Keep logs for the last 7 days
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['timed_rotating_file'],
            'level': 'ERROR',
            'propagate': True,
        },
        'bPortal': {
            'handlers': ['timed_rotating_file'],
            'level': 'ERROR',
            'propagate': False,
        },
    },
}

PWA_SERVICE_WORKER_PATH = os.path.join(BASE_DIR, 'serviceworker.js')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'qxwbi*ws8sq%lna4b)1quats#&7vb2-1u4ii8&frce3wgg__0#'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'portal.apps.PortalConfig',
    'pwa',
    'fontawesomefree'
]

MIDDLEWARE = [
    'django.middleware.gzip.GZipMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'bPortal.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'bPortal/templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'bPortal.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'es-es'

LOCALE_PATHS = (
    os.path.join(BASE_DIR, 'bPortal/locale'),
    os.path.join(BASE_DIR, 'portal/locale'),
)

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')

LOGIN_REDIRECT_URL = '/'

# SuiteCRM settings
# NOTE: You can override this values in custom_settings.py file.
#       Do not change it here.
SUITECRM_DATE_FORMAT = '%Y-%m-%d'
SUITECRM_TIME_FORMAT = '%H:%M'
SUITECRM_DATETIME_FORMAT = '%Y-%m-%d %H:%M:%S'
SUITECRM_CURRENCY_SYMBOL = '€'

# Portal settings
# NOTE: You can override this values in custom_settings.py file.
#       Do not change it here.
DEFAULT_ROLE = 'default'

# NOTE: This field MUST exist on all modules
DEFAULT_ORDER_BY_FIELD = 'date_entered'

# NOTE: Allowed values are 'asc' or 'desc'
DEFAULT_ORDER = 'desc'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# PWA Config
PWA_APP_NAME = 'bPortal'
PWA_APP_DESCRIPTION = "Your bPortal"
PWA_APP_THEME_COLOR = '#0A0302'
PWA_APP_BACKGROUND_COLOR = '#ffffff'
PWA_APP_DISPLAY = 'standalone'
PWA_APP_SCOPE = '/'
PWA_APP_ORIENTATION = 'any'
PWA_APP_START_URL = '/'
PWA_APP_STATUS_BAR_COLOR = 'default'
PWA_APP_ICONS = [
    {
        'src': '/static/portal/img/icons/icon-152x152.png',
        'sizes': '152x152',
        'size': '152x152'
    },
    {
        'src': '/static/portal/img/icons/icon-512x512.png',
        'sizes': '512x512',
        'size': '512x512'

    },
]

PWA_APP_ICONS_APPLE = [
    {
        'src': '/static/portal/img/icons/icon-152x152.png',
        'sizes': '152x152',
        'size': '152x152'

    },
    {
        'src': '/static/portal/img/icons/icon-512x512.png',
        'sizes': '512x512',
        'size': '512x512'

    },

]

PWA_APP_SPLASH_SCREEN = [
    {
        'src': '/static/portal/img/icons/splash-bportal-1242x2688.png',
        'media': '(device-width: 1242px) and (device-height: 2688px) and (-webkit-device-pixel-ratio: 2)'
    }
]

PWA_APP_DIR = 'ltr'
PWA_APP_LANG = 'es-es'

PWA_APP_SCREENSHOTS = [
    {
      'src': '/static/portal/img/icons/app-screenshot_476x744.png',
      'sizes': '476x744',
      'type': 'image/png',
      'platform': 'wide'
    }
]

PWA_APP_DEBUG_MODE = True

try:
    from .custom_settings import *
except ImportError:
    pass
